### ISSUE TITLE
No module named 'pathml.slide'.

### ISSUE THREAD

**Issue by KidElectric** [markowetzlab/pathml-tutorial#1]
Hello and thank you for the wonderful package you are developing! This tutorial looks fantastic but I am running into some issues with the imports.

`from pathml.slide import Slide` yields a ModuleNotFoundError: No module named 'pathml.slide'. 

If I `grep -r "pathml.slide"` on the pathml repository it is not found. Is there a simple replacement to this pathml.slide.Slide class that can be used in the tutorial? 

I am able to run the notebooks in the /pathml/examples folder just fine and the results are very impressive!

**Comment by agberman** [comment]
Hi @KidElectric, sorry to hear you are having this issue! 

How did you install PathML? That line in the tutorial Jupyter notebook assumes you have just cloned the github repo and then added PathML to your path with:
`sys.path.append('/path/to/pathml')`
I assume you have done this though as it is in the pathml-tutorial.ipynb notebook. However, I have seen users do this and also get that error message before which is probably what is happening to you. If so, I recommend installing PathML with pip instead. You can do so by navigating to the `pathml` tutorial containing `setup.py` and running:
`pip install -e .`
After that you can try the same import line as above, and if that doesn't work, try this version of it:
`from pathml import Slide`

Let me know if none of this works for you!

-Adam

**Comment by KidElectric** [comment]
Hi Adam! Thank you for your quick reply!

I installed pathml using the method described in the repo "Installation option 1: pip install". (So that is where the issue is occurring). Should I instead install from pathml repo using the pip install -e . method?

I am running the pathml-tutorial notebook inside the pathml conda env and therefore not using sys.path.append('/path/to/pathml') .

I do not see a setup.py in the pathml-tutorial repo (does the tutorial have a separate installation process?). Thank you for all your help!!!

**Comment by agberman** [comment]
Oh, the pip install -e . method is the pip install method. If you are using the conda environment method, then you do need the line sys.path.append('/path/to/pathml'). Could you try adding that and see if it works with that line?

Ah, my apologies, setup.py is in the pathml repo itself, so [here](https://github.com/markowetzlab/pathml). You can try the pip method I mentioned above by navigating to the pathml directory where you have installed pathml itself (not the tutorial repo). I realize now that you may not have cloned the actual pathml (not tutorial) repo - that is where the file slide.py is and if you have not cloned that repository at the link (https://github.com/markowetzlab/pathml), then that might be your issue. This repository only contains the pathml tutorial, not the library itself.

Let me know if these things work for you!

**Comment by KidElectric** [comment]
OHHHHHH. Wow. I was using https://github.com/Dana-Farber-AIOS/pathml and did not realize this was different than https://github.com/markowetzlab/pathml . Are these completely different projects then? I'm so sorry. I am pretty sure I won't have any problems now that this is more clear to me. I am trying to use your project tutorial though for the record. Thank you for your help!!!

**Comment by agberman** [comment]
Ah, yes, we are completely different projects. Sorry for causing confusion!
