### ISSUE TITLE
progress freezes

### ISSUE THREAD

**Issue by Alan-Py** [markowetzlab/pathml-tutorial#2]
Could you tell me why my progress **freezes** as the first WSI is being run through Slide.detectTissue().Is it my pytorch configuration problem.

**Comment by Alan-Py** [comment]
when i set numWorkers=0, It's getting too slow.

**Comment by agberman** [comment]
Hi @Alan-Py, I am sorry to hear that it is slow for you. We have had users experience this issue before. Apparently it is a PyTorch bug of some kind (see here for example: https://github.com/pytorch/pytorch/issues/15808). What version of PyTorch are you using? Maybe a more recent version will fix the issue for you. If so, I can update the pathml jupyter notebook and pip recipes to use that version instead.

**Comment by Alan-Py** [comment]
Hi,@agberman.I used this command ``conda env create -f /path/to/pathml/pathml-environment.yml`` to create env.According to the dependency of this file, pytorch=1.4

**Comment by Alan-Py** [comment]
Hi,@agberman. I update my torch and cuda. Now I have torch=1.10,cuda=10.2. but when I load the image it still freezes

**Comment by salihkaragoz** [comment]
@Alan-Py Hey,
is there any workaround on this? thanks

**Comment by agberman** [comment]
Hi @Alan-Py apologies fo the delay! I see that you closed the issue, does this mean you have found a solution? Or are you still facing this issue?

**Comment by Alan-Py** [comment]
Hi, @agberman ！I did not find a solution, I used ```num_Workers=0``` to complete the loading of the picture
